name: Deploy on push

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.SSH_HOST }}
          if_key_exists: fail # replace / ignore / fail; optional (default to fail)
      - name:  Pull
        run: ssh redryder@86.56.192.216 "cd /home/redryder/ && /usr/bin/git pull origin main"
